### ISSUE TITLE
Tarefa 13: Desmembração dos Requisitos "Manter"

### ISSUE THREAD

**Issue by melquetrindade** [melquetrindade/sigQueijaria#13]
1. Desmembrar os requisitos Manter Produto e Funcionário em outros 4 requisitos (inserir, alterar, consultar e desativar) na lista de requisitos que consta no documento de visão.
 
2.  Editar a tabela de requisitos envolvidos de todos os user stories que fazem referência aos antigos requisitos para os novos que foram desmembrados no item 1.

**Comment by Thami03** [comment]
Feita por Manuelly
